version: 1
disable_existing_loggers: false
formatters:
  colored:
    class: colorlog.ColoredFormatter
    format: "%(log_color)s[%(asctime)s.%(msecs)03d] %(levelname)s [%(thread)d]%(reset)s - %(message)s"
    log_colors:
      DEBUG: white
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red
  default:
    format: "[%(asctime)s.%(msecs)03d] %(levelname)s [%(thread)d] - %(message)s"
handlers:
  logfile:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/latest.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf-8
  logconsole:
    class: colorlog.StreamHandler
    level: INFO
    formatter: colored
    stream: ext://sys.stdout
loggers:
  root:
    level: INFO
    handlers: [logfile, logconsole]
  uvicorn.access:
    level: INFO
    handlers: [logfile, logconsole]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [logfile, logconsole]
    propagate: no  
  uvicorn.app:
    level: INFO
    handlers: [logfile, logconsole]
    propagate: no  
